name: mysite
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
plugins:
  - jemoji # enables emoji display (disabled in Github pages by default) ref: https://github.com/orgs/community/discussions/22812
